atom/settings-view

- lib/atom-io-client.coffee
- lib/package-manager.coffee
Fix #304, add cache wrapper that was removed when I switched from direct API calls to shelling out to apm.
> Dh themes not showing

- lib/package-snippets-view.coffee
:warning: This should not be merged until atom/atom@184aecb4a4348bd4e58c0d3c35948583665cbfea is released :warning:
This method was added to the snippets module in snippets v0.65.0 so we can avoid using the deprecated event subscription on atom.packages. This is the final deprecation warning in this package.
> Use ::onDidLoadSnippets on snippets module instead of deprecated atom.packages.on

- stylesheets/available-package.less
`min-width` accomplishes the same as the `max()` calculation: make the status indicator halve the size of `@component-padding`, but make sure it's at least 4px. Doing it like this leaves it up to the client to figure it out render-time, which allows `@component-padding` to be in something else than pixels (e.g. rem).
fixes #319
> use min-width to force minimum width to allow @component-padding in rem

- lib/main.coffee
- package.json
- spec/package-updates-status-view-spec.coffee
:warning: Depends on https://github.com/atom/status-bar/pull/51 being merged and released in Atom v0.178 :warning:
> Access status-bar through new service API

- lib/main.coffee
- spec/settings-view-spec.coffee
Support things like this
```coffee
atom.workspace.open('atom://config')
atom.workspace.open('atom://config/themes')
atom.workspace.open('atom://config/install')
```
> Support URIs for each of the panels

- styles/available-package.less
- styles/package-update.less
- styles/settings-view.less
:warning: Don't merge yet. These changes are done on top of #373. Wait until that PR gets merged first.
This PR changes the `font-size` to `em`s. It makes it easier to change most font sizes by only selecting `.settings-view` instead of having to override lots of individual elements.
Fixes: https://github.com/atom/atom/issues/4342
Before:
After:
Customized with:
```css
.settings-view { font-size: 13px; }
```
__Note:__ Not everything can be changes with just the `.settings-view` selector. Controls or buttons still have a fixed px size.
> Variable font size

- lib/package-card.coffee
- spec/installed-package-view-spec.coffee
This adds a spec and fixes enablement styles (whether a package is enabled or disabled) which were going missing when navigating to `detail-package-view`.
Problem:
Disabled in this view
Enabled in this view
> Enablement updates

- lib/package-detail-view.coffee
- styles/available-package.less
- styles/variables.less
Now that #373 has landed, I recently noticed that clicking on the package card body now takes you to the detail view for that package, which is quite nice, but threw me at first. It wasn't clear that anything would happen from clicking the package card body.
This adds a hover state to visually indicate that the user can interact with the package card body. I considered changing the cursor to a pointer too, but I wasn't sure if that'd be too weird - let me know if you think that's worth adding too!
> Add package card hover state

- package.json
The `status-bar` now has a `1.0.0` version of its service, this changes `settings-view` to use that. :sparkles:
> Use new version of status-bar Service API

- coffeelint.json
This adds [coffeelint.json](https://github.com/atom/atom/blob/master/coffeelint.json) from the main Atom repo. 
This is probably not ideal – ideally it would be great if each core package not only had a coffeelint.json file, but was synced with the one in the main Atom repo for maximum DRYness. I'm not really sure how to do this though. This would be easy enough to do in Travis builds (e.g. atom/atom#5982), but there is real value in having coffeelint properly configured during local development too. And git submodules would be a real pain.
If this does seem like the best way to go about it right now I'd be happy to go and add this to all core packages.
/cc @kevinsawicki
> Add coffeelint.json

- lib/package-card.coffee
- spec/available-package-view-spec.coffee
Resolves #355 
I kept the style of the settings button as-is, but we could remove the text if that would be better. Personally, I think we should keep it for clarity. (Maybe remove it on smaller viewport widths?)
I could also add the "scroll to settings" behavior to this PR as well - let me know if you think that would be best.
/cc @thedaniel @simurai @zephraph
> Settings indicator

- lib/install-panel.coffee
This PR updates the help text in the Install panel to correctly reflect context (ie. whether you're searching Packages or Themes).
> Install panel help text tweaks

- lib/installed-packages-panel.coffee
- lib/themes-panel.coffee
- spec/themes-panel-spec.coffee
This PR makes it so that the Packages and Themes panels correctly autofocus when clicking on them within settings-view. (#432 will come in another PR.)
(Should I write specs for this?)
> Focus search fields in installed themes and packages panels

- lib/package-card.coffee
- spec/available-package-view-spec.coffee
Instead of _hiding_ certain buttons, we should _remove_ them so that they do not interfere with how the border radius is applied to the button group.
Before & After
This:
- `.remove()` `install` and `uninstall` buttons from bundled packages.
- `.remove()` `statusIndicator` and `enablement` from themes since you cannot toggle them enabled/disabled.
- adds and updates specs to verify themes do not get `settings` `enablement` or `statusIndicator` buttons
> Use .remove() rather than .hide() for sake of button group

- lib/installed-package-view.coffee
- spec/fixtures/package-with-config/main.coffee
- spec/fixtures/package-with-config/package.json
- spec/installed-package-view-spec.coffee
Fixes https://github.com/atom/settings-view/issues/356 by calling `Package.activateConfig()` if the package is not yet active.
> Activate the config for a package before displaying it

- styles/available-package.less
- styles/settings-view.less
This disables select for package cards and headings, and uses the default cursor for package cards in the detail view.
/cc @simurai @thedaniel
> Normalize cursor and select for headings and package cards

- lib/available-package-view.coffee
- lib/package-card.coffee
- lib/package-manager.coffee
- spec/available-package-view-spec.coffee
- spec/installed-package-view-spec.coffee
- spec/installed-packages-panel-spec.coffee
- spec/package-updates-status-view-spec.coffee
When installing a new package, Settings View will allow package versions to be installed whose `package.json` files require a version of Atom newer than the one currently installed.
See atom/atom#5467 for details.
> Settings view allows installing package versions not supported by the current version of Atom

- styles/settings-view.less
The config menu was actually user selectable before (since it was using the un-prefixed property).
/cc @simurai @thedaniel
> Fix config menu user select

- lib/package-readme-view.coffee
Fixes #469 
Also removes an extraneous `div`.
> Use native keybindings in Readme preview

- lib/package-card.coffee
We've fixed this in places in the past (and there are likely more places that will turn up) where we switch to `remove()` so that the remaining buttons get rounded corners (even with `display: none;` it is still in the dom and messes up the CSS).
This in particular was affecting themes that had no settings and which be default cannot be disabled or have a status indicator. :traffic_light: 
This PR removes instead of hides the three non-relevant buttons.
> Use remove() instead of hide() for button group styling

- styles/available-package.less
- styles/settings-view.less
Came across the need to add this (the div was ending before all of its children) while investigating the _click `package-card` and go to detail view only to have your scroll bar somewhere in the middle_ issue. 
Adding this seems to take care of the scrolling issue and you now start at the top of the detail view. 
_package-detail, before fix, ending too early_
**To Reproduce**
- Open Settings 
- Click Packages, scroll to very last package in list and click the package card
- See that you're in the middle of that package's detail/settings view.
Repeat on this branch, find that you start at the top of the detail/settings view as expected.
cc @simurai for CSS guidance—do you know why this helps and if I've used it correctly?
Closes #472
> Ensure package-detail contains its children

- spec/fixtures/a-theme/package.json
- spec/fixtures/language-test/package.json
- spec/fixtures/package-with-config/package.json
In the near-ish future we'll be checking for correct semver in `package.json` files so we'll need these updated. 
Actually, https://github.com/atom/atom/pull/6645 will need this to pass, also :sparkles:
> Use correct semver in fixture package.json

- lib/atom-io-client.coffee
- lib/keybindings-panel.coffee
- lib/package-manager.coffee
- lib/themes-panel.coffee
- spec/keybindings-panel-spec.coffee
- spec/package-manager-spec.coffee
This adds a `BufferedProcess::onWillThrowError` handler for each spawned `apm` command to handle any process errors instead of showing them as an uncaught notification.
Closes #491
> Handle apm process errors

- styles/settings-view.less
> Prevent repo link being full width

- lib/package-card.coffee
- lib/themes-panel.coffee
- spec/fixtures/syntax-theme-with-config/main.coffee
- spec/fixtures/syntax-theme-with-config/package.json
- spec/fixtures/ui-theme-with-config/main.coffee
- spec/fixtures/ui-theme-with-config/package.json
- spec/settings-view-spec.coffee
- spec/themes-panel-spec.coffee
- styles/settings-view.less
Resolves #323
This adds a settings button for active themes if they have settings.
If One Dark had settings:
TODO:
/cc @braver @simurai @thedaniel @jlord
> Add active theme settings buttons

- lib/package-card.coffee
- lib/package-manager.coffee
This handles Git urls (i.e., `git@github.com:atom/settings-view`) used in the `repository` field for packages. 
Fixes https://github.com/atom/settings-view/issues/505
Links work in `package-detail-view` so I think these two spots should cover it. Before the avatar and repo link were broken. 
It may be a bit verbose and handling the one off case like this may not be ideal to here if there are like 4 other types of urls that may also come through. Thoughts?
cc @kevinsawicki @thedaniel
> Handle Git Repository URLs

- styles/settings-view.less
Fixes checkbox position. Depends on https://github.com/atom/atom/pull/6848
Tested on several themes. All seem good except in Isotope the `.setting-description` is mis-aligned.
> Upgrade Bootstrap

- lib/settings-panel.coffee
This closes https://github.com/atom/language-gfm/issues/104 -- I decided to add just this one config option which was requested in that issue. We can add others as they are requested?
:camera: 
cc @kevinsawicki
> Add softWrapHangingIndent to scopedSettings

- lib/atom-io-client.coffee
This fixes #482.
The glob pattern of `#{login}-*` was erroneously picking up cache files named (for example) `atom-minimap-1234567890` when looking for a file matching `atom-{TIMESTAMP}` (or anyone whose login happened to start with `atom-`).
Changing it to only match trailing digits means the wildcard will only match the timestamp, not timestamp plus any other chars if `#{login}-` happens to be a prefix of somebody else's username.
> Fix avatarGlob to not pick up cached avatars with prefix collisions

- lib/updates-panel.coffee
Now that Atom is at V1.0 we no longer need to show a warning message regarding deprecated APIs being removed in the V1.0 release.
> Remove text related to deprecated APIs being removed in V1.0.

- lib/package-manager.coffee
- spec/package-manager-spec.coffee
Previous to this PR, _all_ disabled packages are assumed installed. https://github.com/atom/settings-view/issues/504 makes this worse by not removing disabled packages from the `disabledPackages` list. So basically, no package that has been disabled and uninstalled can be installed from the UI. :/
In package manager, I'm maintaining a `availablePackageCache` list. This is updated whenever a package is installed, uninstalled, or the package listing is requested from apm.
> Allow uninstalling of disabled packages

- lib/package-detail-view.coffee
Now that updates are displayed inline in package cards, the available updates container above the package card in the package detail view is a bit redundant - this removes it.
/cc @benogle @thedaniel @simurai
> Remove redundant updates container on the package detail view

- lib/themes-panel.coffee
- spec/themes-panel-spec.coffee
Basically something must have changed in Chromium 43+ with regards to how `HTMLSelectElement` behaves along with jQuery's `.prop()` function; using `.prop('selected', true)` no longer works as expected, so the workaround is to fall back to good ol' `.attr('selected', true)`.
Similarly e.g. `.val('atom-light-ui')` no longer works as a means of selecting an option, and the solution is use an equivalent workaround as with `.prop()`.
This might be a bug in jQuery and/or the Chromium build (43.0.2357.65) currently used by Electron, but at least this fixes the problem for the time being.
/cc @atom/feedback
> Fix bugs present when running Atom on Electron

- lib/installed-packages-panel.coffee
- lib/themes-panel.coffee
- spec/installed-packages-panel-spec.coffee
- spec/themes-panel-spec.coffee
- styles/settings-view.less
Minimal implementation of the enhancement requested in #475.
Closes #475
> Collapse packages/themes on click

- styles/package-readme.less
- styles/settings-view.less
This PR improves the styling of package READMEs
Fixes #620
> Package README styling

- styles/package-card.less
> Add spacing when btn-group wraps

- lib/rich-description.coffee
- lib/settings-panel.coffee
- spec/rich-description-spec.coffee
Allows Markdown in setting descriptions, for example from my [tabs-to-spaces package](https://atom.io/packages/tabs-to-spaces) ...
**Before:**
**After:**
Fixes #618
> Allow Markdown in setting descriptions

- styles/settings-view.less
__Before__: Selection made it hard to read in most dark themes.
__After__: Uses `contrast()` to make sure it works for light and dark themes
Fixes https://github.com/atom/atom/issues/8258
> Improve input selection color

- lib/keybindings-panel.coffee
- lib/package-detail-view.coffee
- lib/package-keymap-view.coffee
- spec/installed-package-view-spec.coffee
Adds UI support for toggling keymap activation on a package-level. See https://github.com/atom/atom/pull/8130 for more details.
> Add toggle for keymap activation in package settings

- lib/package-keymap-view.coffee
This fixes https://github.com/atom/settings-view/issues/648 and fixes https://github.com/atom/settings-view/issues/652. 
The reason why that `path.extname(...)` call was failing is that the `path` variable with the `require`d `path` Node module was being overwritten here. This fixes the problem by using a different name for the variable in the function.
Friendly cc to @tmunro @maxbrunsfeld @benogle since this code was added in https://github.com/atom/settings-view/pull/610 as far as I can tell. :v:
> Don't overwrite path module variable

- spec/fixtures/language-test/keymaps/test.cson
- spec/installed-package-view-spec.coffee
:white_check_mark:  Supports #657 by adding test coverage.
> Add test for copying keybinding to clipboard from Package Keymap view

- lib/atom-io-client.coffee
Peep this: https://avatars.githubusercontent.com/technoweenie
This URL hits the GitHub CDN directly. The github.com URL actually _redirects_ to this url. 
```bash
$ curl https://github.com/technoweenie.png
<html><body>You are being <a href="https://avatars0.githubusercontent.com/u/21?v=3">redirected</a>.</body></html>
```
> Use a better avatar url

- lib/settings-view.coffee
- spec/settings-view-spec.coffee
This fixes https://github.com/atom/settings-view/issues/655.
e38bfa5 adds a failing test to demonstrate the problem from the issue. At that commit, running the specs outputs this error:
```
SettingsView
when the package is activated
when atom.workspace.open() is used with a config URI
it opens the package settings view with atom://config/packages/<package-name>
TypeError: Cannot convert undefined or null to object
at SettingsView.module.exports.SettingsView.getOrCreatePanel (/Users/izuzak/github/settings-view/lib/settings-view.coffee:135:38)
```
11c5417 fixes the problem by preventing access to items of `panelCreateCallbacks` when it's not defined, similar to how it's done in other places in that function. Running the specs at this commit outputs 0 failures.
cc @kevinsawicki @thedaniel …
> Prevent accessing panelCreateCallbacks before it is defined

- lib/package-detail-view.coffee
- spec/package-detail-view-spec.coffee
This fixes https://github.com/atom/settings-view/issues/634. It seems that `AtomIoClient.fetchFromCache` calls the callback with [a special combination of values](https://github.com/atom/settings-view/blob/86699fbf3e237b6d659ed28990964c943d05f49a/lib/atom-io-client.coffee#L110-L113) in case the network is unavailable and the package was not found in cache. This special value was handled elsewhere, but needed to be handled in PackageDetailView as well.
068ce24 adds a failing spec, which triggers this error:
```
PackageDetailView
it shows an error when package metadata cannot be loaded from the cache and the network is unavailable
TypeError: Cannot read property 'on' of undefined
at PackageCard.module.exports.PackageCard.handleButtonEvents …
```
> Show error in PackageDetailView when network is unavailable and package is not in cache

- lib/package-card.coffee
- spec/package-card-spec.coffee
If a user clicks the update button for a disabled package, the package should not be enabled after the update. This closes #603. Found this in the [Quality Initiative](https://github.com/atom/atom/issues/7995) post. This affects the Update All button as well.
> Do not enable packages on update

- lib/settings-panel.coffee
Fixes https://github.com/atom/settings-view/issues/670
> Don't render input fields for core.customFileTypes

- lib/general-panel.coffee
- lib/settings-panel.coffee
- spec/general-panel-spec.coffee
- styles/settings-view.less
While we wait for https://github.com/atom/settings-view/issues/284 to be implemented, I think users would find it helpful if they were told that packages have settings of their own, while they're looking at the config settings in the Settings panel.
This pull requests adds two such notes: the first one tells users that packages have additional settings, and the other one tells users the some editor settings can be overridden on a per-language basis. Here's how that looks:
My non-native-English-speaking brain couldn't come up with better text for the notes -- I'd appreciate any suggestions about that.
What do you think, @atom/feedback? :thought_balloon:
> Add notes to Settings panel to point users to package settings

- lib/package-manager.coffee
- spec/package-manager-spec.coffee
This is an attempt to close https://github.com/atom/settings-view/issues/645. 
The problem with that package is that it doesn't have any config settings of it own, but it [does define a grammar](https://github.com/sindresorhus/atom-editorconfig/tree/master/grammars) so it has scoped settings as any other language package.
* 2af57d1 adds a failing spec to demonstrate the problem with the `packageHasSettings` method:
```
package manager
::packageHasSettings
it returns true when the pacakge does not have config, but does define language grammars
Expected false to be true. (spec/package-manager-spec.coffee:191:64)
```
* 9842dd1 modifies `packageHasSettings` so that it returns `true` if a grammar was loaded from that package, using a similar approach as in …
> Show settings button on package cards for packages with grammars

- lib/main.coffee
- lib/package-manager.coffee
- spec/package-updates-status-view-spec.coffee
This was causing a 100% cpu spike on launch with many packages (like Nuclide). Completely fixed my `Atom Helper` CPU issues on launch!
> Fix 100% CPU use on startup. Fixes #555 for me.

- lib/package-manager.coffee
- spec/package-manager-spec.coffee
~~~In progress. One of the specs fails when unfocused, and the cache isn't actually cleared when updating packages thru the API - maybe we're holding on to a bunch of instances of PackageManager or something. We can move the cache somewhere global if that's the case.~~~
Should be fine, I made a point to keep it pretty simple and testable.
cf. #632
> Cache results of ::loadOutdated

- lib/installed-packages-panel.coffee
- spec/installed-packages-panel-spec.coffee
Automatically filter the installed packages list after the packages have finished loading.
Fixes #586 and its duplicates.
> Filter packages after they finish loading

- lib/settings-panel.coffee
This hides the following config settings from the Settings panel so that it doesn't confuse users: `commentStart`, `commentEnd`, `increaseIndentPattern`, `decreaseIndentPattern`, `foldEndPattern`. As mentioned [here](https://github.com/atom/atom/blob/1d5fa01dc46c52ab352622dcc6456fcbcfc7079c/src/config-schema.coffee#L100), these settings are used only by specific languages -- there are no global defaults.
@benogle @kevinsawicki Does this look okay to you? 
Also, I'm wondering if these config settings should be visible in language package settings? Currently, they are not visible, i.e. they're not listed [here](https://github.com/atom/settings-view/blob/b9567cd50448b91eb8f8f09f1dfe2efff156573b/lib/settings-panel.coffee#L16-L30). From the comment I linked to above it _seems_ as if they …
> Hide config settings defined by language packages

- lib/package-detail-view.coffee
This fixes https://github.com/atom/settings-view/issues/638.
@thedaniel do you remember why you added this in https://github.com/atom/settings-view/pull/614/files#diff-078cae2173fad78e9ce04ce50aa4cf96R95 ? As far as I can tell, the response from the Atom.io API will include a `metadata` hash which has all the required properties, including the missing `version` (e.g. see https://atom.io/api/packages/pdf-view).
> Use metadata returned from atom.io API when creating package card in detail view

- lib/utils.coffee
- spec/package-card-spec.coffee
- spec/utils-spec.coffee
If an author of a package specified 'authorName/packageName' instead
of 'https://github.com/authorName/packageName', the link to the author
and the avatar image would be broken when looking at the package card.
Now the short GitHub URI is converted to a long one and it works.
Before when going to Install and searching for jshint:
After:
Fixes #543
> :bug: Short GitHub URIs missing author info

- lib/collapsible-section-panel.coffee
- lib/installed-packages-panel.coffee
- lib/themes-panel.coffee
- spec/installed-packages-panel-spec.coffee
- spec/themes-panel-spec.coffee
- styles/settings-view.less
If there are no packages or themes in a section, don't show it as collapsible and don't do anything if you click on it.
Packages before:
Packages after:
Themes before:
Themes after:
Fixes #636
> Hide collapse icon when there are no themes/packages

- lib/main.coffee
- lib/package-detail-view.coffee
- lib/package-snippets-view.coffee
- lib/settings-view.coffee
- package.json
- spec/installed-package-view-spec.coffee
- spec/package-detail-view-spec.coffee
- spec/settings-view-spec.coffee
This PR introduces a backward-compatible change to use in conjunction with https://github.com/atom/snippets/pull/182, since we've stopped using `atom.config` as a storage for snippets.
/cc: @nathansobo
> Avoid using snippets via atom.config

- styles/settings-view.less
> align search and error messages

- lib/settings-panel.coffee
- spec/settings-panel-spec.coffee
- styles/settings-view.less
While package settings can have grouped options (see the below example) they are not visually separated. This patch adds a `sub-section-headline` if the group has an explicit `title` set. The visual grouping together with a reasonable title provides a better overview over the settings of a package if the number of options increases.
I didn't use `getSettingTitle` since that would introduce the new headlines where none have been before and I wanted to keep the changes to existing settings minimal.
config:
groupA:
type: 'object'
title: 'Options related to A'
properties:
optionA:
type: 'string'
default: 'default A'
optionB:
type: 'boolean'
default: false
groupB:
type: 'object'
title: 'Options related to B'
properties:
optionC:
type: 'string'
default: ''
optionD:
type: 'boolean'
default: …
> add optional sub-section heading if the settings group has an explicit title

- lib/install-panel.coffee
- lib/package-card.coffee
- lib/package-detail-view.coffee
> Move away from deprecated Electron require syntax

- lib/settings-panel.coffee
- spec/settings-panel-spec.coffee
Add defaults on focus and remove them when input field contains the default.
This should fix #243.
> Add defaults on focus

- lib/settings-panel.coffee
- spec/settings-panel-spec.coffee
- styles/settings-view.less
For a package that has a lot of options, such as [`Atom Beautify`](https://github.com/Glavin001/atom-beautify), it appears to be very difficult for users to find the options they want.
I propose that the groups be collapsable.
- Open by default
```javascript
{
group1: {
title: 'Group 1',
type: 'object',
collapsed: true
}
}
```
- ~~"Collapse all sections" button (like the styleguide has)~~
- ~~Only show "Collapse All" button when there are collapsable sub-sections~~
Open `Group 1`:
Collapsed `Group 1`:
```
_group1: {
title: 'Group 1',
type: 'object',
order: 1,
properties: {
prop1: {
type: 'integer',
title: 'Prop1',
default: 1
},
prop2: {
title: 'Prop2'
default: 1
},
},
},
_group2: {
title: 'Group 2',
type: 'object',
order: 2,
properties: {
prop1: {
type: 'integer',
title: 'Prop1',
default: …
```
> Add collapsable section for option groups

- lib/keybindings-panel.coffee
- spec/keybindings-panel-spec.coffee
Edit: Sorry for not having included more description about the changes in the PR.
Currently, for a keybinding
```
Keystroke: alt-cmd-left
Command: pane:show-previous-item
Source: Core
Selector: body
```
A search like `pane show`, `pane cmd`, `Core`, `pane ` (whitespace at end) would all fail to hit it.
The problem is, for each keybinding, `searchString` is created:
`searchString = "#{selector}#{keystrokes}#{command}#{source}".toLowerCase()`
Then the input is tested to see if it's a substring of it.
This doesn't make sense, as common use cases like the ones I listed above aren't possible with this approach.
Two other small issues:
- Whitespace at the end of input is not trimmed
- `#{source}` refers to the keybinding file location like …
> Allow to search keybindings using multi-keyword query

- styles/settings-view.less
CSS code style. `::` is more preference, than `:`
```css
/* CSS3 syntax */
element::before { style properties }
/* CSS2 obsolete syntax (only needed to support IE8) */
element:before  { style properties }
```
https://developer.mozilla.org/en/docs/Web/CSS/::before
> Minor fix for before pseudo element

- lib/settings-view.coffee
- spec/settings-view-spec.coffee
This is to allow InstalledPackagesPanel to initialise with a previously viewed package and fixes #626.
I renamed `activePanelName` to reflect that it is now a panel object not just the name.
> Set active panel with name and options

- styles/settings-view.less
Same issue as https://github.com/atom/atom/pull/11866
Content that overflows the edge gets cut off and you can't scroll.
Content is "responsive" and the table is scrollable again.
> Fix overflowing of the keybindings panel

- lib/package-card.coffee
- lib/package-manager.coffee
- spec/package-card-spec.coffee
This PR fixes #650 by not removing the settings button and show after a package has been installed that has settings.
For this I had to remove `_.memoize` for `PackageManager#packageHasSettings` as it returned a wrong result, this may effect rendering of longer package lists, but so far I have not noticed any negative effect.
> Show settings after install

- lib/install-panel.coffee
- lib/package-card.coffee
- lib/package-manager.coffee
- styles/package-card.less
This implements sorting of packages based on #384.
Currently it sorts package and theme search results based on downloads count.
> Sort packages search

- lib/editor-panel.coffee
- lib/main.coffee
- lib/settings-view.coffee
- spec/editor-panel-spec.coffee
- spec/general-panel-spec.coffee
- spec/settings-view-spec.coffee
The Settings tab within Settings was getting very long and is already broken into Core and Editor.
This PR renames the current tab Core and moves Editor out to its own tab, as shown;;
> Move the editor settings to their own tab

- styles/settings-view.less
All other interactable items in the status bar have a pointer cursor and text underline on hover. It makes sense to apply that style to the package update notification as well since clicking it opens a new tab.
This is similar to https://github.com/atom/about/pull/32, which adds a pointer to the squirrel icon.
I understand there is a PR to _remove_ all `cursor:pointers` but until that happens I think it's worth having consistency across the status bar modules. [The branch](https://github.com/atom/atom/pull/7698) has definitely gotten a little stale.
> Added styles to status bar notification to make the interaction more obvious

- lib/package-manager.coffee
This is a fix for issue #532 - Package cards in Updates panel don't change state when updates are done installing.
Before this commit, updating a package that had activation commands would cause the package card to display the loading state forever.
The cause of the issue was that the update process was waiting for the updated package to activate. This was a problem because calling `activatePackage` will only immediately activate a package that doesn't have any activationCommands.
The proposed fix is to wait for the package to load and then attempt to activate the package without waiting.
> Wait for updated package to load and then try to activate

- README.md
- lib/main.coffee
- lib/settings-view.coffee
- lib/system-windows-panel.coffee
- package.json
- spec/settings-view-spec.coffee
Adds a new System tab on Windows that allows configuration of the OS shell integration options for things like the file handler, file context menu and folder context menu.
> Add new System tab for Windows shell integration options

- lib/editor-panel.coffee
- lib/general-panel.coffee
- lib/install-panel.coffee
- lib/settings-view.coffee
- lib/system-windows-panel.coffee
- lib/themes-panel.coffee
- Core Settings title now uses icon-settings like sidebar
- System Settings now title-cased
- Install title now uses icon-plus like sidebar
- Theme title now uses icon-paintcan like sidebar
> Unify icons between tabs and titles

- styles/settings-view.less
Sets `overflow: auto` for settings-view to prevent overflow.
see #821
> Fix #821 Settings-view overflows when pane is narrow

- lib/package-card.coffee
Also, send assertion failures back to bugsnag when this happens.
Fixes #766
> Avoid throwing null pointer exceptions when package update fails

- lib/package-detail-view.coffee
If atom is meant to be a hackable editor why would you hide the button to edit the source code?
There's a bug report by someone else here https://github.com/atom/settings-view/issues/617.
> Always show view code button

- styles/settings-view.less
Fix height of "Choose a Theme" and "Install Packages" panels when running Atom with recent versions of Electron (currently 1.3.3). See https://github.com/tensor5/arch-atom/issues/38.
> Height incorrectly set to 100%

- lib/settings-panel.coffee
- spec/settings-panel-spec.coffee
Fixes https://github.com/atom/settings-view/issues/774
> In scoped editor settings panels, use unscoped setting value as its default

- lib/package-card.coffee
- lib/package-manager.coffee
- lib/updates-panel.coffee
- spec/installed-packages-panel-spec.coffee
- spec/package-card-spec.coffee
- spec/updates-panel-spec.coffee
Previously, we attempted to unload and reload packages after they were updated. This has never really worked and has produced a lot of confusion. The reason it doesn't work is that Node's `require` system caches values for every path, so only new files in the package would be successfully required. We could potentially do some fancy stuff to track dependencies and delete them all from the cache on reload, but I understand that it's basically impossible to unload and reload native addons in Node, which would mean even that would be a partial solution. So instead we'll just prompt the user to restart.
Depends on https://github.com/atom/atom/pull/12733 to display a "restart" button, but is  backward compatible by just making the user restart manually in older versions.
Closes …
> Prompt to restart Atom after updating packages rather than trying to "hot reload" them

- lib/install-panel.coffee
Current behavior:
This pull request moves packages which names contain the search query to the top, below the exact hit. 
I personally think that this will surface more relevant packages in a partial search but it might bury some popular packages, for instance when searching `file-icons` then `file-type-icons` will rank lower, but it will surface more packages that contain the search term. A better long term solution would be to use a scoring system that would view each word individually.
Feedback would be appreciated.
> Prioritize close matches in install search results

- styles/settings-view.less
We are in the process of removing the shadow DOM boundary from `atom-text-editor` elements. This pull request upgrades existing selectors so that they:
* Stop using `:host`.
* Stop using `atom-text-editor::shadow`.
* Prepend syntax class names with `syntax--`.
/cc: @simurai
> Stop using shadow DOM selectors

- lib/package-keymap-view.coffee
- lib/settings-panel.coffee
- lib/system-windows-panel.coffee
- styles/settings-view.less
Now that we have the `input-checkbox` styles from `atom-ui`, we can remove the custom styling in settings-view.
> Use input-checkbox styles

- lib/package-grammars-view.coffee
- spec/fixtures/language-test/grammars/c.json
- spec/installed-package-view-spec.coffee
It isn't uncommon for language packages to include a few "helper" grammars for internal use. Most of the time, this is to provide embeddable highlighting for one or more "real" grammars. These shouldn't be visible to the end user... and certainly not with a title of `undefined Grammar`:
**Complements:** atom/grammar-selector#34
> Hide unnamed grammars in package-detail view

- lib/settings-panel.coffee
This setting was removed from Atom Core a while ago, and having it here just produces erroneous text fields in all of the language packages.
This closes #873
> Remove normalizeIndentOnPaste from scopedSettings

- lib/install-panel.coffee
- lib/main.coffee
- lib/package-manager.coffee
- lib/package-updates-status-view.coffee
- lib/settings-view.coffee
- lib/themes-panel.coffee
- spec/installed-package-view-spec.coffee
- spec/package-updates-status-view-spec.coffee
Instead of removing the updates tooltip as soon as it gets clicked, dynamically update the number of updates left in the tooltip as individual packages get updated.  When there are no outdated packages left, the tooltip will disappear.
Closes #511
> Dynamically update the updates tooltip

- lib/updates-panel.coffee
`getInstalled()` doesn't affect `getOutdated()` and was just slowing the process down if we had cached data from `getOutdated()`.
Here's two GIFs, the first one before the change and the second one after.  Pretty big difference :).  Sorry for the extra non-Atom stuff in the background.  Had to resize the Atom window but forgot to resize licecap.
Before:
After:
Fixes #409, closes atom/atom#6945.
Though this doesn't do anything about the case when you click the updates tile a sufficiently long time after Atom loads, causing Atom to check for updates again since the outdated cache expired.  I think that's fine though.
/cc @Caged
> Drastically improve loading time of updates panel

- lib/main.coffee
- lib/package-card.coffee
- lib/updates-panel.coffee
- spec/package-card-spec.coffee
- spec/updates-panel-spec.coffee
These conditionals were added in #851 and are no longer needed as Atom 1.12 is now stable.
> Remove unnecessary conditionals

- lib/package-manager.coffee
- lib/package-updates-status-view.coffee
- spec/package-manager-spec.coffee
- spec/package-updates-status-view-spec.coffee
Closes #883
Some things to note:
* The tile changes have been extracted into a helper `updateTile` method which I think helps streamline and deduplicate things (see below).
* This PR fixes a bug in my previous PR where I accidentally set the priority of the tile to 0 when reinitializing it instead of -99.  The new helper method takes care of this.
* This PR also fixes a different bug in my previous PR where we were trying to call `tooltip.dispose()` on a non-existent tooltip if the Check for Updates button was pressed.  Whoops!
* I fixed a bug in PackageManager where the `package-updating` event was being generically emitted through Emitter rather than through the dedicated `emitPackageEvent` helper method.  This means that `theme-updating` will now start to be emitted for themes.
TODO:
> Indicate when a package is updating in the status bar tile

- lib/main.coffee
They're not related at all.
As a result, this should speed up the time it takes to initialize the status bar tile, as we no longer have to go through `getInstalled()` (which is slow).
Furthermore, to prevent a slowdown in activation time, I moved the localStorage check to _before_ we call `getInstalled()`.  This way we won't have to do work for nothing.
> Move deprecated notifications out of consumeStatusBar

- lib/package-manager.coffee
- spec/package-card-spec.coffee
- spec/package-manager-spec.coffee
Because it's already there for us!  Why use our own implementation?
Fixes #817
TODO:
> Use atom.packages.getAvailablePackageNames

- lib/package-detail-view.coffee
- spec/package-detail-view-spec.coffee
For some reason disabled core packages don't have `@pack.path`.
Fixes #730
> Show core package READMEs even when disabled

- lib/package-card.coffee
- lib/updates-panel.coffee
- spec/package-card-spec.coffee
- spec/updates-panel-spec.coffee
If an update fails, then there's obviously still a new version/sha available.  Keep the update button there so that users can retry.  Fixes #886.
> Don't hide the update button if updates fail

- lib/package-manager.coffee
- lib/updates-panel.coffee
- spec/package-manager-spec.coffee
- spec/updates-panel-spec.coffee
Some general improvements to the updates panel.
* Don't hide the Update All button when checking for updates: instead, disable it and only hide it after we've checked for updates and none are available.
* When explicitly clicking on the "Check for Updates" button, clear the outdated packages cache and actually recheck for updates.
* Disable checking for updates when packages are updating.  This is to prevent the state getting completely messed up.  More details in the commit description of 1011f43621ca1615734866ecb9a481c7f4ac9a20.
* When the Update All button is clicked, only packages that are not already being updated are updated.  This may fix #879?  Not sure, couldn't reproduce it but I didn't really try to.
Note: there seems to be an issue where the metadata returned by …
> Improve updates panel UX

- lib/package-manager.coffee
Chromium does a good job at reading system proxy settings which means a lot of what Atom needs to do goes through the correct proxies.
The apm command line being a regular node app and not an Electron/Chromium app does not read or have access to these proxy settings and so fails when trying to connect if you are using a proxy.
This change determines what http and https proxy servers to use based on Chromium's session.resolveProxy call with atom.io and then sets the http_proxy and https_proxy environment variables that apm then uses.
Alternative designs include;
1. Moving apm functionality entirely into Atom - too much work at this time and would mess up command-line scripting
2. Editing the apm.rc file with the proxy settings - too destructive
People behind proxy servers can use apm with …
> Apply Chromium proxies to env vars for apm

- lib/settings-panel.coffee
Add a tooltip with the default value to the settings view.
Couple questions:
- At the moment i add the tooltips to the left. This means that the appear in roughly the same location for each setting, however, for input field with long defaults, this also means that the tooltip might fall outside the screen. Especially with the tree view 'off'.
- I don't know how to write tests to check if the tooltips are present when there is a default value.
Anyone got a couple pointers to help me finish this?
> Show default in tooltip when present in settings - Resolves #268

- lib/main.coffee
- lib/settings-view.coffee
- spec/settings-view-spec.coffee
- spec/themes-panel-spec.coffee
Recent changes to the status bar tile necessitated that a single PackageManager instance was used throughout the codebase so that events would be caught correctly.  Unfortunately, there was one instance that I forgot to change: when deserializing, two PackageManagers get created (one in `main`, one in `settings-view`), leading to the status bar not receiving any events.  This PR fixes that.
None.
The status bar and other parts of the code will work correctly when the Settings View is deserialized.
None.
Fixes #902
Note: I am not sure how to add a spec for …
> Use a single package manager when deserializing

- README.md
[This jumped out at me](https://github.com/atom/settings-view#customize), so I had to fix it:
> Use correct grammar to highlight code sample

- spec/settings-view-spec.coffee
This has been relying on the pane to be created synchronously when
dispatching the command (and calling `open()`), which would only happen
in certain conditions. After atom/atom#13977, `open()` is more reliably
async so we need to take that into account.
> Wait for `open()` to complete before considering command done

- lib/package-manager.coffee
- lib/updates-panel.js
- spec/package-manager-spec.coffee
- spec/updates-panel-spec.coffee
Prevent package whose names are listed in `core.versionPinnedPackages` from being shown for automatic updating. This is only prevented through the Atom UI. Using `apm` from the command line will not respect the `core.versionPinnedPackages` setting.
* Specify the version number in addition to the package name
* Decided that simply specifying the package name simplified the code and was probably good enough for the target use case
* If people want to update to a newer version, they would need to update the package _and_ update their config file
* Prevent the packages from being updated within `apm` as well
* Figured that people should be able to easily update their pinned version if they wanted but keep the package pinned
People can prevent Atom from recommending to update to a newer …
> Prevent version pinned packages from showing as needing updates

- lib/package-keymap-view.js
- spec/installed-package-view-spec.coffee
Collect the keybindings created by each package from the package itself rather than filtering them from the `atom.keymaps` global. `atom.keymaps` does not include bindings from disabled packages or from packages with disabled keybindings, but the package's `.keymaps` property does.
As a side effect, we'll no longer be relying on the convention of beginning command names with the package name to identify which commands are associated with a package. Weird Things will happen if you deviate from this with the present scheme!
Fixes #946. Depends on atom/atom-keymap#218 for `atom.keymaps.build()`.
> Display keybindings even when disabled

- lib/package-updates-status-view.js
- spec/package-updates-status-view-spec.coffee
Update the status bar tile when packages with updates are uninstalled.
None.
Removes another case of the tile being inconsistent.
None.
Fixes #964
> React to uninstalls in the status bar tile

- lib/settings-panel.js
- spec/settings-panel-spec.coffee
Prior to this PR, the scoped setting default was ignored and the unscoped default was used instead.  That was done in #841 to fix #774 (not being able to change scoped settings if the unscoped value was also changed).  However, that caused a different bug where if the scoped default was different than the unscoped default, it was impossible to change the scoped value to the unscoped default.  This PR aims to fix both issues.  First, we search for the scoped default (without looking at the `config.cson`).  Then we check the unscoped default.  If the …
> Fix calculation of scoped setting defaults

- lib/package-updates-status-view.js
- spec/package-updates-status-view-spec.coffee
Redo of #970 because it wasn't picking up my second commit.  Accidentally found this bug yesterday when an update failed two times.  Instead of removing the failed status when the package successfully updates, instead remove it when the package begins updating.  This fixes an issue where if the same update failed multiple times, `onPackageUpdateFailed` would return early and not remove the failed update from the updating list, resulting in the status bar eternally thinking that the package was still updating.
Change some logic around in …
> Wipe failed status from status bar when an update is retried

- lib/keybindings-panel.js
- spec/keybindings-panel-spec.coffee
Escape backslashes before copying a keybinding to the keyboard.
None.
Backslashes will be escaped properly.
None.
Fixes #363
> Escape backslashes when copying keybindings

- spec/installed-package-view-spec.coffee
Wait for all the snippets to load before asserting that snippets show up in the Settings View.  The callback I'm using is already in use in `package-snippets-view.js`.
Before: 50 pass/50 fail
After: 100 pass
Fixes #973
> Wait for snippets to load before checking snippets

- lib/updates-panel.js
Somewhere down the line the order of these two buttons in the DOM were switched.  This led to the Check for Updates button receiving the margin-left property and not the Update All button (since the CSS selector was `.update-all-button:last-child`).  Switch them back around and remove some unneeded classes like `.pull-right` (the two are on the right to begin with) and an extra `.btn`.
| Before | After |
| ------- | ------ |
| ![update-button-margin-before](https://user-images.githubusercontent.com/2766036/29009468-907fbe68-7af1-11e7-8e26-325b3820f723.png) | ![update-button-margin-after](https://user-images.githubusercontent.com/2766036/29009457-7c731f0a-7af1-11e7-82c6-76c4b17a95d5.png) |
Sidenote: the `.update-all-button` class is very wrong on the "Check for Updates" button, but too …
> Fix update button order

- lib/package-updates-status-view.js
- spec/package-updates-status-view-spec.coffee
Reverts an overzealous change from #971.  This should go out in the next Atom 1.20.0-beta hotfix.
/cc @Ben3eeE, @joefitzgerald.
> Do not test for update object equality

- styles/settings-view.less
I changed the selector to `.themes-picker-item .btn` so that it won't break if another button is added.
Fixes atom/atom#15563
@simurai
> Add correct styling to syntax theme settings button

- lib/main.coffee
- package.json
Adds a URI handler for `atom://settings-view/show-package?package=package_name` that will open the package's page in Atom.
Depends on https://github.com/atom/atom/pull/11399
> Add URI handler to show package pane

- lib/package-detail-view.js
- lib/package-readme-view.js
- spec/fixtures/package-with-readme/README.md
- spec/package-detail-view-spec.coffee
When rendering package READMEs, whilst sanitizing the source image, URLs are now checked to see if they are absolute or relative and if they are relative then they are resolved appropriately. For example for non-installed plugins the base URL would be the GitHub repo however if they are installed it uses the path of the installed plugin.
**Before**:
**After**:
I considered attempting to match up each image in the Markdown with its counterpart on its Atom.io page or its README on GitHub and using those URLs. I chose this solution in the end as it was much simpler and in the cases I've tested still seems to work.
Packages using relative URLs for images in their README files as recommended by GitHub will now be rendered correctly
Any URL scheme not recognized by the code I have written will …
> Relative image URLs in package READMEs are now resolved correctly

- lib/settings-panel.js
- lib/settings-view.js
- lib/uri-handler-panel.js
- styles/settings-view.less
This adds settings and logs related to URI handler registration, etc. to the settings view. It will include:
* A button to make Atom the default atom:// URI handler if it's not already
* A tri-state setting for what to do when Atom starts and isn't the default protocol handler
* Always ask
* Always automatically register
* Never register
* A list of recent URIs handled and which package handled them (with a button to disable said package)
Depends on https://github.com/atom/atom/pull/11399
> Add pane for URI protocol registration settings

- styles/settings-view.less
This hides the collapsed icon when there are no items available.
No more box.
None
Fixes #1009
> Hide the collapsed icon when there are no items

- lib/package-card.js
- spec/package-card-spec.coffee
This is a quick fix for #879.  `PackageCard::update` would not return a Promise when there was no update available, which was causing exceptions in methods that expected `update` to always return a Promise.
I would like to revisit the Updates panel code to make it smarter and not attempt to call `update` on packages that have no updates available.  But as for this specific change, there are no alternatives as it is strictly a bugfix to consistently return the same type.
One less bug.
None.
Fixes #879
> Always return a promise for PackageCard::update

- spec/installed-package-view-spec.coffee
I realized that `onDidLoadSnippets()` might already have been called by the time we hook it, meaning that we'll never receive the event.  Therefore I have changed our approach to rely on polling `provideSnippets().bundledSnippetsLoaded()` instead, which should ensure that we will continue if snippets have already been loaded by the time we reach the waitsFor.
I considered moving this waitsFor block above the waitsForPromise block so that it had a higher chance of catching the `did-load-snippets` event but that would still have the chance to fail.
Less …
> Poll bundledSnippetsLoaded() rather than waiting for a hook

- lib/main.js
- lib/package-manager.coffee
Properly dispose of any disposables on deactivation to prevent lingering traces of Settings View from lying around.
None.
Better package deactivation.
None.
This addresses #764 to the maximum extent possible without changing code in Atom core.
> Deactivate correctly

- lib/main.js
- lib/package-manager.coffee
Reverts atom/settings-view#1027
> Revert "Deactivate correctly"

- lib/package-card.js
- lib/updates-panel.js
Add a summary of updated packages to the restart notification.
The summary contains package name, last version and new version:
Maybe some kind of scroll list is needed for large ammounts of updates,
since the restart button might disappear at the bottom.
A more compact summary compared to the possibly large large list of package cards.
The option to see pre and post update version when the update process is finished (package cards do not show the past version post update) .
> feat(update-panel): add summary to notification

- lib/atom-io-client.coffee
- lib/install-panel.js
- lib/package-manager.coffee
- package.json
- spec/install-panel-spec.coffee
- spec/package-manager-spec.coffee
This pull request implements the search capability equivalent to previously used `apm search --json (--packages|--themes)? term`, sorted by download count in descending order. Measuring the web request that is done inside `apm`, with ~118ms network latency it takes around 750-800ms to respond (according to Chrome devtools), whereas the total execution time for `apm search` takes around 1.5 seconds.
Searching for `github` and measuring using `performance.now()`:
Before: `packageManager.search()` 1587ms average
After: `client.search()` 853ms average
Although using just `apm` would be cleaner, this is a significant gain in terms of perceived responsiveness. Search functionality doesn't depend on `apm` existing in any way and being one of the most frequently used parts of settings-view where …
> Speed up search by not invoking apm

- lib/main.js
- lib/settings-view.js
- spec/settings-view-spec.coffee
Fix #723
Condition #723 happens is
- When workspace have two or more panes and setting-view is already opened in currently not active pane.
- User invoke `settings-view:open`(it try to open `atom://config`)
Why happens is
- `atom.worksace.open` try to open already opened `setting-view` item also in different pane
- If setting-view is already opened in workspace, activate it's pane in opener so that `workspace.open` always open already opened item in workpace.
- This hacky help is necessary since **singleton settingView** item is opened as **different URI**(workpace.open cannot open existing seting-view item by URI). 
- It eventually simulate `searchAllPanes: true` option in `workspace.open`.
Plus(I can remove this refactoring part if requested)
- Add `SettingsView::showPanelForURI` method …
> always open existing setting item in 'settings-view:open' command

- lib/install-panel.js
When searching packages in the "Packages" section in settings, it searches automatically upon typing ("onDidStopChanging").
This functionality is missing in the "Install" section. Searching should be consistent and more user friendly. When the user finishes typing, it should just search for him.
Example:
The previous implementation was search by pressing "enter".
A better UX and more consistent experience
More network requests
> Perform search in "Install Panel" automatically after user stops typing

- lib/updates-panel.js
- package.json
- spec/updates-panel-spec.coffee
Implements an update queue for the Update All process.
Instead of opening one instance of APM per update this PR introduces ```maxApmInstances```
to limit the number of simultaniously running updates.
Setting ```maxApmInstances``` to a value < 1 will fall back to the old behaviour, starting all updates at once.
+ prevents lower end systems from sluggishness through high cpu usage, or even crashing
+ unblocks #937  (I will do a follow up PR soon after merge)
+ closes #756 
+ closes #746 
+ closes #546 
+ closes #519 
This might slow down the update process on beefy systems (with non optimal settings).
> feat(update-panel): implement update queue

- lib/settings-panel.js
- spec/settings-panel-spec.coffee
The default value of a configuration setting is shown next to it in a tooltip. Configuration settings also support an [`enum` key](https://atom.io/docs/api/v1.28.1/Config#enum) with `description` properties which will be displayed instead of the raw values. This description, however, only applies to the drop-down itself but not the tooltip. For example:
Since the `value` and `description` properties may not be similar, one can’t be sure which value is actually the default one. The “Color Profile” setting above is actually a good example: What’s `default`?
This pull request changes the tooltip to show the description instead (so it matches the drop-down’s choices):
The default value could also be marked in the drop-down itself, for example by suffixing “(default)”. The proposed version was …
> Show enum description as default in tooltip

- lib/main.js
- lib/package-detail-view.js
- lib/package-snippets-view.js
- spec/fixtures/language-test/snippets/bar.json
- spec/installed-package-view-spec.coffee
- styles/settings-view.less
Add an “Enable” checkbox inside the snippet view to add/remove the current package from the snippets blacklist.
`PackageSnippetsView` is rehabilitated and made to show a package’s snippets (should a package have any snippets to display). The issues described in #1076 have been fixed.
An “Enable” checkbox has been added at the top of the section — identical to the one at the top of a Keybindings panel. Just as unchecking the Keybindings panel’s Enable checkbox immediately disables that package’s key bindings, unchecking the Snippet panel’s Enable checkbox immediately disables all snippets provided by that package. No reloading of the window is necessary.
The snippets themselves are listed in the table with columns for prefix, name, scope, and body. Since the body of a snippet is arbitrary …
> Ensure snippets are displayed in a package’s settings view.

- lib/package-readme-view.js
- spec/fixtures/package-with-readme/README.md
- spec/package-detail-view-spec.coffee
The sanitize function merges the package path with the image source,
a check is needed for base64 encoded images, to ensure they are properly
shown in the package readme view.
This PR adds a regex based check for base64 encoded images in package README files, with a similar syntax as surrounding checks.
None.
Prior to this change, all base64 images in README files would break, when viewed from the settings view.
None.
Fixes https://github.com/atom/settings-view/issues/1030
> :bug: Fix base64 encoded image viewing in package README files.

- lib/atom-io-client.coffee
- spec/atom-io-client-spec.coffee
In #1014, package searches were changed to use the atom.io API endpoint rather than calling out through apm.  As part of that change, parsing of the resulting JSON data was delegated to the `request` module.  Interestingly, `request` [does not throw an error](https://github.com/request/request/blob/a6741d415aba31cd01e9c4544c96f84ea6ed11e3/request.js#L1146-L1152) when it fails to parse the response body as JSON and instead returns the raw body as a string.  The new package search code failed to account for this scenario, which resulted in #1052.
There are …
> Make sure body was successfully parsed as JSON before filtering

- styles/settings-view.less
Fixed misaligned theme dropdown in Themes panel. When changing the size of the window the dropdowns for choosing UI Theme and Syntax Theme was not aligned. Fixed so the Syntax Theme dropdown is at the same height as UI Theme.
As this only exists of CSS changes to match the other dropdown's behaviour no other alternatives was considered.
This fixes the bug with misaligned dropdowns and makes it more aesthetically pleasing. 
None that I can see.
Misaligned theme dropdowns in Themes panel #995
> Fix themes dropdown alignment described in issue #995

- lib/package-card.js
- lib/updates-panel.js
- spec/package-card-spec.coffee
- spec/updates-panel-spec.coffee
When installing a package from [git url](https://github.com/atom/apm/pull/518) this [bug](https://github.com/atom/settings-view/issues/1056) occurs on the first update.
The second update shouldn't be affected because the package gets convertet from git style to normal as part of the update.
This PR makes the code for the detail message more robust and adds sha's for git packages:
closes: #1056
To reproduce the bug reset a git package:
1. `apm install thomaslindstrom/color-picker`
2. `cd ~/.atom/packages/color-picker`
3. `g stash`
4. `g reset --hard a296114f3d0deec519a41f4c62e7fc56075b7f01`
5. `g stash pop`
6. replace the sha in `package.json`
Btw. what is the point of having git packages in the first place, when we convert them after the first update?
> fix(restart-notification): undefined latestVersion

- lib/settings-view.js
- spec/settings-view-spec.coffee
Fix #1003
- Invalidate `PackageDetailView` panel cache kept in `this.panelsByName[pkgName]` on activating/deactivating package.
- Original issue #1003 was happened by returning cached panel.
- Includes some cleanup
- Remove unused variables/ library require
- Quit awkward conditional initialization of instance variable
Ideally setting-vew should refresh pkg detail-view on clicking "Enable", "Disable" timing, but that improvement should come as different PR.
Enabling/Disabling package from setting-view and accessing setting menu is more intuitive.
Nothing.
#1003
> Invalidate cached pkg detail panel  on activate/deactivate package

- lib/atom-io-client.coffee
- spec/atom-io-client-spec.coffee
- spec/package-detail-view-spec.coffee
The `fetchFromCache` method looks up if there is cached data.  Then, if it hasn't expired yet or Atom doesn't have internet access, it returns the cached data.  Otherwise, if there was no cached data and Atom wasn't online, it used to return the empty object `{}` "so callers don't crash".  Ironically, this very line causes the featured packages lookup to "crash" with an exception since it expects an array.  Therefore in this PR I have removed the special-casing and always return `null` without internet access and let the callers deal with it (they already …
> Remove broken offline special-casing when retrieving cached data

- lib/atom-io-client.coffee
- lib/install-panel.js
- spec/install-panel-spec.coffee
This PR removes the custom sorting logic that the setting-view performs after getting search results from apm.  My reasoning is that with the [recent changes](https://github.com/atom/settings-view/issues/984#issuecomment-354875049) to apm's sorting we should no longer need to add extra sorting in settings-view.  This also means that the search results will be consistent regardless of whether the search was executed through settings-view, apm, or https://atom.io/packages/search.
None.
Removal of code that had minimum benefits as well as consistency with …
> Display search results in order returned from apm

- lib/package-card.js
- styles/package-card.less
This adds some space before the version of packages.
Easier to read.
None
Fixes #1098
> Fix spacing of package versions

- styles/settings-view.less
This is a follow up to #1105 that tweaks a bit the breadcrumb styling:
- Less height
- Smaller font
- Bolder active state
- Even divider spacing
Before | After
--- | ---
- Less vertical space needed
- Visual improvements
None
Follow up to #1105
> Sticky breadcrumbs II

- lib/package-detail-view.js
- styles/settings-view.less
This PR makes the sub-sections "sticky". Also, the collapsed and uncollapsed icons got replaced with "chevrons" and placed in front.
- Easier to see what belongs to which subsection.
- Easier to see if a sub-section is collapsed or not. The fold icons are hard to differentiate.
- Sub-section can be collapsed after scrolling down.
None.
Inspired by #1105
> Sticky sub-sections

- styles/settings-view.less
This fixes the 1px gap above sticky headers. Note: It's only reproducible on retina screens. Maybe a rounding error?
Before | After
--- | ---
N/A
Less distracting.
If themes want to add a border or so, it might get cut off.
Fixes #1111
> Fix sticky header gap

- styles/package-card.less
This adds some space between version and deprecated label.
Before | After
--- | ---
Easier to read
None
Fixes #1113
> Fix space between version and deprecated label

- lib/settings-panel.js
- spec/settings-panel-spec.coffee
This PR adds a description to configurations of type 'object'.
Currently a 'description' for a configuration of type 'object' is ignored.  This is problematic because objects allow for a grouping or subset of options which may need a description applying to all of them.  Without the object description field, settings under a scope are forced to repeatedly describe something. 
No alternate designs were considered.  I figured this was a straight forward change and I honestly have no clue what an alternate solution could even be.
- Removes the need to repeat descriptions for object properties [such as these](https://github.com/olsonpm/prettier-atom/blob/permalink-for-pr/src/config-schema.json#L180-L276)
*Note: the above link contains a repetitive note inside each scoped config description*
- …
> add 'description' for object setting

- styles/docks.less
This improves the layout of the settings-view when moved to the left/right dock.
There are a [few options](https://github.com/atom/settings-view/pull/1115#issuecomment-466282855) for the navigation.
When moving the settings-view to a dock, it allows you to keep the editor in sight. Great when making changes to the settings and then see the result in the editor.
- It is a bit experimental with just some CSS overrides.
- The Keybindings need to be scrolled horizontally and fit better in the center.
- Adds extra maintenance cost.
N/A
> Support settings-view in docks

- lib/settings-panel.js
- spec/settings-panel-spec.coffee
`array` config type will allow an escaped comma in the value.
the config value will be `["1", ",", "2"]`
Comma can be used in array values.
none
fixes #1102
closes #1101
> Comma value in array

- lib/keybindings-panel.js
- spec/keybindings-panel-spec.coffee
Escapes quotes and backslashes better in the keybinding-to-string function.
In addition to linked issue, this is a keybinding I found on my own Atom that needs quote escaping
```cson
'atom-text-editor[data-grammar~=\'css\']':
'ctrl-alt-c': 'css-declaration-sorter:sort'
```
Without this PR, it wouldn't escape the value quotes.
Also tidied up the composition part, which was really hard to read IMO. Now it's a clean single line with well defined newlines and spacing.
Considered `CSON.stringify(...)`, but 
(1) it does a lot of extra work for little benefit, …
> Escape CSON correctly

- lib/atom-io-client.coffee
Use the repository URL returned from the atom.io server query as the URL of the repository, instead of the one defined by the package itself in its own metadata to prevent potential for impersonation of other authors.
Before:
After:
Potential enhancements to this include making the atom.io server reject package versions where the metadata in the package doesn't agree with the repository the version is coming from. Since this hasn't been in place from the start though we need to either purge all packages from atom.io that don't match or implement something …
> Use server repository instead of package defined

- lib/settings-panel.js
- spec/settings-panel-spec.coffee
- styles/settings-view.less
This pull request adds support for a `radio` option in the config schema, for `enum` config values. If `radio` is `true`, then the enum will be displayed as a group of radio buttons. 
*Edit by @rsese to add screenshot from https://github.com/atom/settings-view/pull/1089#issuecomment-435422204*
I chose to add an option here because it seemed like the easiest way to not break existing config files, and to maintain backwards compatibility for new config files. If a config file using the `radio: true` feature is processed by an older version of Atom, the …
> Add option to display config enums as radio buttons

- spec/installed-package-view-spec.coffee
This PR attempts intermittent failures of tests that interact with snippets. I think these failures are caused by the following race condition:
* The tests activate the `snippets` package first.
* The snippets package loads bundled snippets, then reads all loaded packages in an async function.
* The tests then activate the `language-test` package asynchronously in a `waitsFor` block.
* Most of the time, the `waitsFor` block runs before the async function that reads loaded packages in the `snippets` package, but this isn't guaranteed.
* If the `waitsFor` block runs *after* the async code in the snippets package, snippets from the `language-test` package are never loaded and the tests fail.
I think this what is happening. Hopefully I am right and CI will pass now. 🤞
> Attempt to fix unreliable tests

- lib/package-detail-view.js
- lib/package-manager.coffee
- spec/fixtures/package-with-bugs-property-email/package.json
- spec/fixtures/package-with-bugs-property-url-string/package.json
- spec/fixtures/package-with-bugs-property-url/package.json
- spec/fixtures/package-without-bugs-property/package.json
- spec/package-detail-view-spec.coffee
The existing implementation ignores the package.json `bugs` property, when deriving the report issue link. The proposed solution checks if the `bugs` property is a string or an object, if it's an object it's parsed for an URL or email, according to the [NPM package specification](https://docs.npmjs.com/files/package.json#bugs). The repository issue URL is used as fallback.
None.
Replaces the old getRepositoryUrl with a new getRepositoryBugUri that respects the `bugs` property in `package.json`. 
None.
For Atom packages using an issue tracker outside of GitHub or an email, the **Report Issue** button will now link to the correct place.
As the proposed solution uses the old solution as fallback, there's no identified drawbacks.
#966
#1040
> Enhanced the report issue link derivation to respect the package.json bugs property

- spec/updates-panel-spec.coffee
Jasmine 1.3 queueing makes async testing weird. In this case, we resolve a promise with the expectation that it asynchronously displays a notification. Then, in a `waitsFor` block on the next line, we subscribe to `onDidAddNotification`. The problem is that this `waitsFor` block might not even be *run* before the notification gets displayed. So the notification is displayed before we even subscribe to `onDidAddNotification` and the `waitsForBlock` gets stuck. This kind of thing seems especially frequent on Windows/AppVeyor.
The ideal fix would be to convert all these tests to JS and use `async`/`await`. Then we could *synchronously* subscribe to `onDidAddNotification` after resolving the promise and avoid this race. But in this case, I think using a looser condition should work as well.
> Use a less timing-sensitive condition to hopefully fix flaky test

- lib/atom-io-client.coffee
- spec/atom-io-client-spec.coffee
We might end up calling it in unrelated code paths, such as `@atom/notify`, which is why I'm making this change.
> Don't mock JSON.parse globally in test

- lib/atom-io-client.coffee
Two levels of callbacks = two fat arrows needed. I'll try to add a spec or two for this.
Fixes atom/atom#19293
> Pass `this` into the promise function

- styles/settings-view.less
This PR aligns the `.color .setting-description  margin-top: -0.5em; pulls the description to about the same distance in e.g. checkbox settings descriptions,
Ive illustrated the description to a gif for visualization of what this PR does.
Thought about  actually aligning both checkbox and swatches to be middle aligned to settings titles as well as the color settings description fix in the PR Something like (can be tested by adding this to your Atom stylesheet.
```css
.settings-view {
input[type="checkbox"] {
margin: 0.21em 0.75em 0 -2.25em;
}
.color { …
```
> color .setting-description alignment

- styles/settings-view.less
An upgrade to [electron 6](https://github.com/atom/atom/pull/21079) broke the scrolling in the package settings pane.
Fixes: https://github.com/atom/settings-view/issues/1155
> Fix scroll in package settings pane

- lib/package-card.js
- lib/package-readme-view.js
- lib/rich-description.js
- package-lock.json
- package.json
This:
- Uses marked instead of roaster which was deprecated years ago.
- Updates marked to the latest version
- The old roaster was deprecated years ago and can bring many bugs and security issues. 
- The new marked has many improvements to its engine. Follows the latest GitHub behavior and has fixed a huge number of bugs, security issues, etc.
N/A
Closes #1148 
Fixes #500
> Use marked instead of roaster + update marked

- spec/package-manager-spec.coffee
The command is meant to fail therefore there is no need to use proxy. Using proxy in this case causes the test to timeout.
> Update spec to not use proxy settings when calling apm

- lib/package-card.js
- lib/updates-panel.js
- spec/package-card-spec.coffee
- spec/updates-panel-spec.coffee
This pull request adds a button to skip restarting after package updating. 
The cross button in the top right corner does the same thing but based on my statistics, the users don't use it often, and they think restarting in the middle of their work session is forced by Atom. This button explicitly gives them the option to skip restarting after updates. This is useful if they are in the middle of a work session and restarting Atom is considered a disturbance.
The tests are added for the "I'll do it later" button.
The rest of the tests should pass.
> feat: add explicit button to skip restarting after package updating

- lib/updates-panel.js
- package-lock.json
- package.json
This PR updates async dependency:
- queue.drain is async now, no need to manually make it async
- queue.push accepts an array
The docs for asyncQueue
https://caolan.github.io/async/v3/docs.html#queue
This speeds up updating the packages.
N/A
> fix: update async dependency

- lib/package-detail-view.js
- Use a `fs.statSync` to check if the file is available before calling `fs.readFileSync`
See https://github.com/atom/atom/issues/22109 
- Add a `try catch` block around `fs.readFileSync` because the call to `fs.readFileSync` could throw an error in the event a file is not available.
```js
try {
readme = fs.readFileSync(this.readmePath, {encoding: 'utf8'})
} catch(err) {
readme = null
}
```
Improved user experience. We should not be throwing an error if the README file is not available, we should fail safely. 
N/A
https://github.com/atom/atom/issues/22109
> Catch README file not found error

- lib/package-detail-view.js
Maybe atom should warn instead of ignoring this
Also I'm not sure what happens if the readme (or even the whole folder) is manually deleted
No errors
Silently ignored
https://github.com/atom/atom/issues?q=is%3Aissue+is%3Aopen+PackageDetailView.renderReadme
Resolves atom/atom#23475
Resolves atom/atom#22699
Resolves atom/atom#22499
Resolves atom/atom#22435
> fix: Don't error if the readme doesn't exist
