atom/settings-view

menus/settings-view.cson

Some commands changed in the latest update, and they were not updated
in this file. I also added missing commands, and updated the menu item
labels to be more complete & accurate
Fixes atom/atom#4993

:bug: Update menu commands

---

stylesheets/available-package.less

Fixes Styling Regression, when package has no Image (Fixes #337)

---

lib/settings-panel.coffee
stylesheets/settings-view.less

Depends on https://github.com/atom/atom/pull/4930

Add color settings

---

lib/main.coffee
lib/themes-panel.coffee
spec/themes-panel-spec.coffee

:warning: Depends on atom/atom#4937 :warning:

Fix deprecated calls

---

spec/installed-packages-panel-spec.coffee

Signed-off-by: Max Brunsfeld <maxbrunsfeld@gmail.com>

Remove parens to fix test

---

lib/package-detail-view.coffee
lib/updates-panel.coffee
package.json
spec/atom-io-client-spec.coffee

Follow on to #447 
/cc @mnquintana

Enable coffeelint on CI

---

spec/available-package-view-spec.coffee

@jlord This is just to fix my comment over on #450 - it'll merge into your branch. :beers:

Refactor settings indicator spec

---

lib/package-detail-view.coffee

Fixes https://github.com/atom/settings-view/issues/465.
Travis is refusing to run the tests for an unknown reason. However, I ran them locally and I'm getting failures which are also present on master (they don't seem to be related to this PR).
cc @nathansobo @mnquintana

Check if package is loaded before activating config

---

lib/install-panel.coffee

Using correct variable to display the packages path on "Install"

---

lib/package-detail-view.coffee
lib/settings-view.coffee
spec/settings-view-spec.coffee

Reload package before rendering details

---

lib/atom-io-client.coffee
spec/atom-io-client-spec.coffee

Handles (and tests the handling) of errors that come from using glob.
Closes #454

Handle errors from glob

---

lib/keybindings-panel.coffee
spec/keybindings-panel-spec.coffee

Case-insensitive keybindings search. Fixes #496

---

lib/main.coffee
spec/package-updates-status-view-spec.coffee

This will show when atom starts up if there are packages to upgrade

Add upgrade notification

---

.coffeelintignore
coffeelint.json
lib/atom-io-client.coffee
lib/installed-packages-panel.coffee
lib/keybindings-panel.coffee
lib/package-card.coffee
lib/package-readme-view.coffee
lib/settings-panel.coffee
lib/themes-panel.coffee
lib/updates-panel.coffee
package.json

Refs https://github.com/atom/atom/issues/5982

Update coffeelint support

---

lib/package-updates-status-view.coffee
spec/package-updates-status-view-spec.coffee

Remove bang from package update indicator

---

lib/install-panel.coffee
lib/installed-packages-panel.coffee
lib/package-card.coffee
lib/package-detail-view.coffee
lib/package-manager.coffee
lib/package-snippets-view.coffee
lib/package-update-view.coffee
lib/settings-view.coffee
lib/themes-panel.coffee
lib/updates-panel.coffee
package.json

Continuation of #538 from @mgarciaisaia.
Closes #538 
Closes #537

Use event-kit

---

lib/general-panel.coffee
lib/install-panel.coffee
lib/installed-packages-panel.coffee
lib/keybindings-panel.coffee
lib/main.coffee
lib/package-card.coffee
lib/package-detail-view.coffee
lib/package-grammars-view.coffee
lib/package-update-view.coffee
lib/settings-panel.coffee
lib/settings-view.coffee
lib/themes-panel.coffee
lib/updates-panel.coffee
spec/install-panel-spec.coffee
spec/package-card-spec.coffee
spec/settings-view-spec.coffee

Closes #559
Closes #557
Closes #562
Closes #556 with f47609116be0453a481e0cb9044e48c87d3a73d3
Closes #545
Closes #535
Closes #541

Fix several bugs and regressions

---

lib/installed-packages-panel.coffee
lib/package-card.coffee
lib/themes-panel.coffee
lib/utils.coffee
spec/package-card-spec.coffee
spec/themes-panel-spec.coffee
styles/available-package.less

Also use the `List`/`ListView` in the themes panel.
Closes #529

Fix uninstall button to have user feedback

---

lib/package-detail-view.coffee
spec/fixtures/package-with-readme/README.md
spec/fixtures/package-with-readme/package.json
spec/installed-package-view-spec.coffee

Fixes https://github.com/atom/settings-view/issues/550
/cc @atom/feedback

Display Readmes for symlinked packages

---

lib/install-panel.coffee
lib/package-detail-view.coffee
lib/updates-panel.coffee

remove margins from alert info

---

lib/atom-io-client.coffee

Set User-Agent header when making network requests to GitHub/Atom.io

---

lib/main.coffee
package.json

Depends on https://github.com/atom/atom/pull/10764

Specify deserializer in package.json

---

lib/atom-io-client.coffee

Missed this one in the last PR.

Another require fix for remote

---

lib/install-panel.coffee
lib/installed-packages-panel.coffee
lib/package-card.coffee
lib/package-detail-view.coffee
lib/package-manager.coffee
lib/themes-panel.coffee
package.json
spec/installed-packages-panel-spec.coffee
spec/themes-panel-spec.coffee

Signed-off-by: Michelle Tilley <binarymuse@github.com>

[WIP] Display and manage Git-based packages

---

lib/install-panel.coffee
lib/package-card.coffee
lib/package-manager.coffee
spec/install-panel-spec.coffee
spec/package-manager-spec.coffee

* Fix activating packages after installing
* Improve UI around installing Git-based packages
Depends on https://github.com/atom/apm/pull/525
Signed-off-by: Michelle Tilley <binarymuse@github.com>

Improve installing Git-based packages

---

lib/settings-panel.coffee
spec/settings-panel-spec.coffee
spec/themes-panel-spec.coffee

Use existential operator for existence

---

lib/settings-panel.coffee
spec/settings-panel-spec.coffee

Support descriptions for enum values in config

---

lib/package-readme-view.coffee
spec/fixtures/package-with-readme/README.md
spec/installed-package-view-spec.coffee
spec/package-detail-view-spec.coffee

Fixes #628, https://github.com/atom/atom/issues/8349, https://github.com/atom/atom/issues/11862.

Disable all checkboxes within package readme. Fixes #628

---

lib/package-detail-view.coffee

Fix: handlers re-registered on package reinstall

---

lib/package-detail-view.coffee

Do not show startup time for disabled/not installed packages. Fixes #852

---

README.md

Fix minor mistake in documentation.
N/A
Better documentation
N/A
N/A

Correct menu item for windows

---

lib/updates-panel.coffee
styles/settings-view.less

This allows the action buttons in the updates-panel header wrap properly on smaller screen sizes.
(see images below)
None just stayed consistent with the current ui.
Clean & functional ui on smaller screens
None
None

Make update buttons wrap properly

---

lib/package-manager.coffee

Depends on https://github.com/atom/atom/pull/13976.
By using this new API we will be able to communicate asynchronously with the main process to resolve proxies, as opposed to using `remote` and blocking the renderer process during startup.

Use `atom.resolveProxy` when possible

---

lib/settings-panel.js
spec/settings-panel-spec.coffee

|Before|After|
|-------|------|
|![settings-view-zero-default-before](https://user-images.githubusercontent.com/2766036/28198155-ed871820-6829-11e7-82f4-666df61879d2.png)|![settings-view-zero-default-after](https://user-images.githubusercontent.com/2766036/28198150-d11dfe42-6829-11e7-8ce4-e1839d9129d1.png)|
Can be considered as a follow-up to #784.
None.
Default will be displayed.
None.
#783

Add placeholder text and tooltips for zero defaults

---

lib/settings-panel.js

add tabType as a scoped setting so it's easier to discover and configure when languages override it
N/A
Easier to configure
N/A
Fixes https://github.com/atom/settings-view/issues/835

Add tabType as a scoped setting

---

lib/package-readme-view.js
package.json
spec/fixtures/package-with-readme/README.md
spec/package-detail-view-spec.coffee

Switch to more comprehensive HTML sanitization for rendering README markdown content.

Use DOMPurify for README sanitization

---

.travis.yml

Switch objective-c for node_js so Travis can use linux instead of OS X

---

lib/uri-handler-panel.js

Update URI handler args

---

lib/settings-panel.js
spec/settings-panel-spec.coffee

Fixes https://github.com/atom/atom/issues/16817
Refs https://github.com/atom/settings-view/pull/974

Fix setting validation

---

lib/collapsible-section-panel.js
lib/editor-panel.js
lib/error-view.js
lib/general-panel.js
lib/install-panel.js
lib/installed-packages-panel.js
lib/keybindings-panel.js
lib/list-view.js
lib/list.js
lib/main.js
lib/package-card.js
lib/package-keymap-view.js
lib/package-readme-view.js
lib/package-snippets-view.js
lib/rich-description.js
lib/settings-panel.js
lib/settings-view.js
lib/system-windows-panel.js
lib/themes-panel.js
lib/updates-panel.js
package-lock.json
package.json

Lint JavaScript code with Standard.
N/A
More consistent code style and less chance of errors.
None - these changes are all stylistic.
N/A

Lint with Standard

---

lib/settings-panel.js

Fix some stuff from an old PR.

Fix up standard formatting

---

lib/package-card.js
lib/package-readme-view.js
lib/rich-description.js
package-lock.json
package.json

Equivalent to https://github.com/atom/notifications/pull/206
**Untested**

⬆️ marked to 4.0.10

---

lib/package-card.js

Removed `href` attributes for links related to package author. Replaced them with callbacks.
No other alternate designs were considered
May fix
- atom/atom#22383
None that I can think of
atom/atom#22383

fix: Attempt to fix atom/atom#22383
